# Generated by Django 4.2 on 2026-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_task_deadline_task_project_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
